/*
 * cli_setup.c
 *
 *  Created on: 2023/09/19
 *      Author: ch.wang
 */

#include <common/FreeRTOSCli/cli_api.h>
#include <FreeRTOS.h>
#include "FreeRTOS_CLI.h"
#include <string.h>
#include "ble_stack_api.h"
#include <ti/bleapp/ble_app_util/inc/bleapputil_api.h>

#define MAX_COMMAND_COUNT 2


static BaseType_t prvTaskStatsCommand( char *pcWriteBuffer,
                                          size_t xWriteBufferLen,
                                          const char *pcCommandString );
static BaseType_t prvATpADDRCommand( char *pcWriteBuffer,
                                          size_t xWriteBufferLen,
                                          const char *pcCommandString );

void cli_init(void){
    uint8_t i;
    static const CLI_Command_Definition_t xTasksCommand[MAX_COMMAND_COUNT] =
    {
     {
        "tasks",
        "tasks : Test command.\r\n",
        prvTaskStatsCommand,
        1
     },
     {
       "AT+ADDR",
       "AT+ADDR : Get device address.\r\n",
       prvATpADDRCommand,
       0
     }
    };

    for(i = 0; i < MAX_COMMAND_COUNT; i++)
    {
        FreeRTOS_CLIRegisterCommand( &xTasksCommand[i] );
    }
}

static BaseType_t prvATpADDRCommand( char *pcWriteBuffer,
                                          size_t xWriteBufferLen,
                                          const char *pcCommandString )
{
    uint8_t getAddr[6] = {0};
    bleStk_getDevAddr(TRUE, getAddr);
    char* strAddr = BLEAppUtil_convertBdAddr2Str(getAddr);
    strcpy(pcWriteBuffer, strAddr);
    return pdFALSE;
}

static BaseType_t prvTaskStatsCommand( char *pcWriteBuffer,
                                          size_t xWriteBufferLen,
                                          const char *pcCommandString )
{
    /* For simplicity, this function assumes the output buffer is large enough
    to hold all the text generated by executing the vTaskList() API function,
    so the xWriteBufferLen parameter is not used. */
    ( void ) xWriteBufferLen;

    /* pcWriteBuffer is used directly as the vTaskList() parameter, so the table
    generated by executing vTaskList() is written directly into the output
    buffer. */
    //vTaskList( pcWriteBuffer + strlen( pcHeader ) );
    strcpy(pcWriteBuffer, "\r\nTasks Status");

    /* The entire table was written directly to the output buffer.  Execution
    of this command is complete, so return pdFALSE. */
    return pdFALSE;
}
